name: Build/Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to be set with npm'
        required: true
  release:
    types: [created]
  
jobs:
  build-windows:
    name: Electron Build Windows
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EP_PRE_RELEASE: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        working-directory: client
        run: npm i --dev

      - name: Electron Build
        working-directory: client
        run: npx electron-builder build --publish always

      - name: ZIP Portable
        run: powershell Compress-Archive ./client/dist/win-unpacked openchat-portable-win.zip

      - name: ZIP server
        run: powershell Compress-Archive ./server/ server.zip

      - name: List Files
        run: |
          ls
          cd client/dist
          ls
    
      - name: Upload server zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: server.zip
          asset_name: server.zip
          tag: ${{ github.ref }}
          overwrite: false

      - name: Upload portable zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: openchat-portable-win.zip
          asset_name: openchat-portable-win.zip
          tag: ${{ github.ref }}
          overwrite: false
  
  build-macos:
    name: Electron Build macOS

    runs-on: macos-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EP_PRE_RELEASE: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        working-directory: client
        run: npm i --dev

      - name: Electron Build
        working-directory: client
        run: npx electron-builder build --publish always

  build-linux:
    name: Electron Build Linux

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EP_PRE_RELEASE: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        working-directory: client
        run: npm i --dev

      - name: Electron Build
        working-directory: client
        run: npx electron-builder build --publish always