name: Build/Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to be set with npm
        required: true
  create:
    tags:
      - '*'
  release:
    types: [created]
  
jobs:
  build-windows:
    name: Electron Build Windows
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EP_PRE_RELEASE: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        working-directory: client
        run: npm i --dev

      - name: Electron Build
        working-directory: client
        run: npx electron-builder build --publish always

      - name: ZIP server
        run: powershell Compress-Archive ./server/ server.zip

      - name: List Files
        run: |
          ls
          cd client/dist
          ls

  # zip-server:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v1

  #     - name: List Files
  #       run: ls -la
      
      # - name: Upload zip to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ${{ matrix.file }}
      #     asset_name: Server
      #     tag: ${{ github.ref }}
      #     overwrite: false